
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thisath Dewsen
 */
public class Returnn extends javax.swing.JFrame {
        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
    /**
     * Creates new form IssueBook
     */
    public Returnn() {
        initComponents();
        //conn = Javaconnect.ConnecrDB(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        txtbid = new javax.swing.JTextField();
        txtbname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfine = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lateDays = new javax.swing.JTextField();
        txttoday = new javax.swing.JTextField();
        issudate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtduedate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        back = new rojeru_san.complementos.RSButtonHover();
        clear = new rojeru_san.complementos.RSButtonHover();
        returnn = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();

        setPreferredSize(new java.awt.Dimension(1366, 947));

        jPanel1.setBackground(new java.awt.Color(240, 168, 76));
        jPanel1.setPreferredSize(new java.awt.Dimension(914, 651));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Return Book");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Today");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("BookID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Issue Date");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("BookName");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("MemberID");

        txtmid.setBackground(new java.awt.Color(255, 255, 204));
        txtmid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtbid.setBackground(new java.awt.Color(255, 255, 204));
        txtbid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbidKeyReleased(evt);
            }
        });

        txtbname.setBackground(new java.awt.Color(255, 255, 204));
        txtbname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Fine");

        txtfine.setBackground(new java.awt.Color(255, 255, 204));
        txtfine.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtfine.setForeground(new java.awt.Color(255, 102, 102));
        txtfine.setText("Rs.0.00");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Late Days");

        lateDays.setBackground(new java.awt.Color(255, 255, 204));
        lateDays.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txttoday.setBackground(new java.awt.Color(255, 255, 204));
        txttoday.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        issudate.setBackground(new java.awt.Color(255, 255, 204));
        issudate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Due Date");

        txtduedate.setBackground(new java.awt.Color(255, 255, 204));
        txtduedate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        back.setBackground(new java.awt.Color(240, 240, 240));
        back.setBorder(null);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        back.setText("Back");
        back.setColorText(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(240, 240, 240));
        clear.setBorder(null);
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cleaning.png"))); // NOI18N
        clear.setText("Clear");
        clear.setColorText(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        returnn.setBackground(new java.awt.Color(240, 240, 240));
        returnn.setBorder(null);
        returnn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checklist (1).png"))); // NOI18N
        returnn.setText("Return");
        returnn.setColorText(new java.awt.Color(0, 0, 0));
        returnn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnnActionPerformed(evt);
            }
        });

        rSButtonHover1.setText("Print");
        rSButtonHover1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGap(196, 196, 196))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(returnn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addGap(113, 113, 113)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtfine, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtbid, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                            .addComponent(txtbname)
                                            .addComponent(txtmid)
                                            .addComponent(txttoday)
                                            .addComponent(issudate)
                                            .addComponent(txtduedate))
                                        .addComponent(lateDays, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(54, 54, 54)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtbid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtbname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtmid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issudate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtduedate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttoday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lateDays, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rSButtonHover1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtfine, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(930, 690));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyReleased
        // TODO add your handling code here:
        try{
            conn = Javaconnect.ConnecrDB();
            String sql = "SELECT `mid`, `bname`, `i_date`, `r_date` FROM `issue` WHERE bid = '"+txtbid.getText()+"' AND status = 'Issued'";
            pst =conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next()){
                
                txtbname.setText(rs.getString("bname"));
                txtmid.setText(rs.getString("mid"));
                issudate.setText(rs.getString("i_date"));
                txtduedate.setText(rs.getString("r_date"));
                String r_date =  rs.getString("r_date");
                //txtbname.setText(rs.getString(r_date));
                
                LocalDate today = LocalDate.now();//calculate current date
           
                txttoday.setText(today.toString());
                
                LocalDate rdate = LocalDate.parse(r_date); 
                
                Long day_gap = ChronoUnit.DAYS.between(rdate,today);  // diference between due date and current date
                
                    if(day_gap >0){
                        
                    lateDays.setText(day_gap.toString());
                    
                    }else{
                    lateDays.setText("0");
                    }
                    
                 //calculate fine
                 int fine = 0;
                 
                 if(day_gap > 0 && day_gap <= 30){
                        fine = 1;
                 }else if(day_gap > 30 && day_gap <= 90){
                        fine = 40;
                 }else if(day_gap > 90 && day_gap <= 180){
                        fine = 80;
                }else if(day_gap > 180){
                        fine = 100;
                }
                 
                String iid = Integer.toString(fine);
                txtfine.setText(iid);
                
                }else{
                
                    txtbname.setText("");
                    txtmid.setText(""); 
                    issudate.setText("");
                    txtduedate.setText("");
                    txttoday.setText("");
                    lateDays.setText("");
                    txtfine.setText("0");
                
                }
            
            bill();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                pst.close();
                rs.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        
    }//GEN-LAST:event_txtbidKeyReleased

    private void returnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnnActionPerformed
        // TODO add your handling code here:
        String bid = txtbid.getText();
        String bname = txtbname.getText();
        String mid = txtmid.getText();
        String rdate = txttoday.getText();
        String ldate = lateDays.getText();
        String fine = txtfine.getText();
        
        try{
            conn = Javaconnect.ConnecrDB();
            String sql = "INSERT INTO `returndeatil`(`bid`,`bname`, `mid`, `return_date`, `late_days`, `fine`) VALUES ('"+bid+"','"+bname+"','"+mid+"','"+rdate+"','"+ldate+"','"+fine+"')";
            pst = conn.prepareStatement(sql);
            pst.execute();
            updateIssueTable();//update bookstatus after return in book table 
            updateBookStatus();
            JOptionPane.showMessageDialog(rootPane,"Book Returned Succesfully");
            clearField();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e);
        }finally{
            try {
                pst.close();
                rs.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    
    }//GEN-LAST:event_returnnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         clearField();
    }//GEN-LAST:event_clearActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
           try {
                // TODO add your handling code here:
                txtbill.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Returnn.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    //update book status after return
    private void updateBookStatus(){
        
        
        try{
            conn = Javaconnect.ConnecrDB();
            String sql = "UPDATE book  SET status = 'Active' WHERE bid ='"+txtbid.getText()+"'";
        
        pst = conn.prepareStatement(sql);
        pst.execute();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            try {
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    
    
    private void updateIssueTable(){//when book is returned status of issue table will be updated to returned
        
        try{
            conn = Javaconnect.ConnecrDB();
            String sql = "UPDATE issue  SET status = 'Returned' WHERE bid ='"+txtbid.getText()+"' AND mid = '"+txtmid.getText()+"'";
        
        pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(rootPane, "Book Status Updated Succesfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            try {
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        
    }
    
    
    
    
    private void bill(){
        txtbill.setText("Public Library"+"\n"
                        +"Ranpokunagama"+"\n\n"
                        +"Fine Recipt"+"\n"+"\n"
                        +"=================="+"\n"
                        +"Member id\t"+ txtmid.getText()+"\n"
                        +"Late days\t" + lateDays.getText()+"\n"
                        +"Fine\t\t" + txtfine.getText()+"\n"
                        +"=================="
        
        );
    }
    
    
       private void clearField(){
        
        //clear textfield
   
        txtbid.setText("");
        txtbname.setText("");
        txtmid.setText(""); 
   
        issudate.setText("");
        txtduedate.setText("");
        txttoday.setText("");
        lateDays.setText("");
        txtfine.setText("0");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returnn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover back;
    private rojeru_san.complementos.RSButtonHover clear;
    private javax.swing.JTextField issudate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lateDays;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover returnn;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txttoday;
    // End of variables declaration//GEN-END:variables
}
